VulkanRenderer: Fix compile error on glibc 2.43
sa_handler may not be a direct member of struct sigaction, in glibc 2.43
it may be defined as part of a union of sa_handler and sa_sigaction,
then a preprocessor macro is defined for compatibility purposes.
Here it expands as `sa{.__sigaction_handler.sa_handler = ...}` which
is not supported in C++.

/home/sapphire/code/Cemu/src/Cafe/HW/Latte/Renderer/Vulkan/VulkanRenderer.cpp: In function ‘int BreathOfTheWildChildProcessMain()’:
/home/sapphire/code/Cemu/src/Cafe/HW/Latte/Renderer/Vulkan/VulkanRenderer.cpp:346:29: error: expected primary-expression before ‘.’ token
  346 |         struct sigaction sa{.sa_handler = [](int unused){_exit(1);}};
      |                             ^